-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.pessoa
(
    id_pessoa integer NOT NULL,
    nome_pessoa text NOT NULL,
    email_pessoa text NOT NULL,
    tel_pessoa text NOT NULL,
    senha_pessoa text NOT NULL,
    PRIMARY KEY (id_pessoa)
);

CREATE TABLE IF NOT EXISTS public.produtos
(
    id_produto integer NOT NULL,
    nome_produto text NOT NULL,
    "vlrCompra_produto" money NOT NULL,
    "vlrVenda_produto" money NOT NULL,
    qtd_produto integer NOT NULL,
    PRIMARY KEY (id_produto)
);

CREATE TABLE IF NOT EXISTS public.vendas
(
    id_venda integer NOT NULL,
    id_pessoa integer NOT NULL,
    data_venda date NOT NULL,
    pgto_venda text NOT NULL,
    "vlrTotal_venda" money NOT NULL,
    PRIMARY KEY (id_venda)
);

CREATE TABLE IF NOT EXISTS public.vendas_itens
(
    id_venda_itens integer NOT NULL,
    id_venda integer NOT NULL,
    id_produtos integer NOT NULL,
    PRIMARY KEY (id_venda_itens)
);

ALTER TABLE IF EXISTS public.vendas
    ADD CONSTRAINT pessoa_venda FOREIGN KEY (id_pessoa)
    REFERENCES public.pessoa (id_pessoa) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.vendas_itens
    ADD CONSTRAINT "venda_idVenda" FOREIGN KEY (id_venda)
    REFERENCES public.vendas (id_venda) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.vendas_itens
    ADD CONSTRAINT "produto_Intens" FOREIGN KEY (id_produtos)
    REFERENCES public.produtos (id_produto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;